source_sh ${srcdir}/emulparams/elf_i386.sh
SCRIPT_NAME=elf
OUTPUT_FORMAT=elf32-i386
TEXT_START_ADDR=0x08048000
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
COMMONPAGESIZE="CONSTANT (COMMONPAGESIZE)"
ARCH=i386
MACHINE=
NOP=0x90909090
GENERATE_SHLIB_SCRIPT=no
GENERATE_PIE_SCRIPT=no
NO_SMALL_DATA=yes
SEPARATE_GOTPLT=12
